#!/usr/bin/env python3
"""Best-effort Catalyst Data export updater for this article.

This script updates simple repo-level CSV exports if the catalyst_data_exports
folder exists or can be created. It is intentionally conservative: it appends
or replaces rows for this article slug without requiring a database.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ARTICLE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ARTICLE_ROOT.parents[2]
EXPORTS = REPO_ROOT / "catalyst_data_exports"
EXPORTS.mkdir(exist_ok=True)
META = json.loads((ARTICLE_ROOT / "metadata.json").read_text(encoding="utf-8"))
SLUG = META["slug"]
TITLE = META["title"]
SERIES = META.get("series", "International Law")
ARTICLE_PATH = f"articles/international-law/{SLUG}"


def read_csv(path: Path):
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def upsert(path: Path, key: str, fieldnames, new_rows):
    rows = read_csv(path)
    existing = {row.get(key): row for row in rows if row.get(key)}
    for row in new_rows:
        existing[row[key]] = row
    ordered = list(existing.values())
    write_csv(path, fieldnames, ordered)

primary = read_csv(ARTICLE_ROOT / "data" / "primary_sources.csv")
secondary = read_csv(ARTICLE_ROOT / "data" / "secondary_sources.csv")

upsert(
    EXPORTS / "article_repository_map.csv",
    "article_slug",
    ["article_slug", "article_title", "series", "repository_path", "wordpress_slug", "status"],
    [{
        "article_slug": SLUG,
        "article_title": TITLE,
        "series": SERIES,
        "repository_path": ARTICLE_PATH,
        "wordpress_slug": SLUG,
        "status": "published-ready",
    }],
)

source_rows = []
for row in primary:
    source_rows.append({
        "source_id": f"{SLUG}__{row.get('source_id','')}",
        "article_slug": SLUG,
        "source_title": row.get("source_title", ""),
        "source_type": row.get("source_type", ""),
        "institution_or_author": row.get("institution", ""),
        "year": row.get("year", ""),
        "url": row.get("url", ""),
        "notes": row.get("notes", ""),
    })
for row in secondary:
    source_rows.append({
        "source_id": f"{SLUG}__{row.get('source_id','')}",
        "article_slug": SLUG,
        "source_title": row.get("title", ""),
        "source_type": "secondary",
        "institution_or_author": row.get("author", ""),
        "year": row.get("year", ""),
        "url": row.get("url", ""),
        "notes": row.get("notes", ""),
    })

upsert(
    EXPORTS / "all_article_sources.csv",
    "source_id",
    ["source_id", "article_slug", "source_title", "source_type", "institution_or_author", "year", "url", "notes"],
    source_rows,
)

instrument_rows = []
for row in primary:
    instrument_rows.append({
        "instrument_id": f"{SLUG}__{row.get('source_id','')}",
        "article_slug": SLUG,
        "title": row.get("source_title", ""),
        "instrument_type": row.get("source_type", ""),
        "institution": row.get("institution", ""),
        "year": row.get("year", ""),
        "url": row.get("url", ""),
        "notes": row.get("notes", ""),
    })

upsert(
    EXPORTS / "legal_instruments.csv",
    "instrument_id",
    ["instrument_id", "article_slug", "title", "instrument_type", "institution", "year", "url", "notes"],
    instrument_rows,
)

tag_rows = [{"article_slug": SLUG, "tag": tag} for tag in META.get("tags", [])]
upsert(
    EXPORTS / "tags.csv",
    "tag_key",
    ["tag_key", "article_slug", "tag"],
    [{"tag_key": f"{SLUG}__{r['tag']}", **r} for r in tag_rows],
)

compat_row = {
    "article_slug": SLUG,
    "article_title": TITLE,
    "repository_path": ARTICLE_PATH,
    "primary_sources": str(len(primary)),
    "secondary_sources": str(len(secondary)),
    "status": "catalyst-data-ready",
    "notes": "Generated by article updater script.",
}
upsert(
    EXPORTS / "compatibility_audit.csv",
    "article_slug",
    ["article_slug", "article_title", "repository_path", "primary_sources", "secondary_sources", "status", "notes"],
    [compat_row],
)

summary_path = ARTICLE_ROOT / "outputs" / "catalyst_data_article_export.json"
summary_path.write_text(json.dumps({"metadata": META, "sources": source_rows}, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Updated Catalyst Data exports in {EXPORTS}")
